/**
 * Exportación a Software de Simulación
 * Formatos soportados: CDEGS, ETAP, SKM, PSCAD, DigSILENT
 */

/**
 * Valida parámetros antes de exportar
 */
const validateParams = (params, calculations) => {
  const errors = [];
  if (!params) errors.push('Parametros no definidos');
  if (!calculations) errors.push('Calculos no definidos');
  if (!params.soilResistivity) errors.push('Resistividad del suelo no definida');
  if (!params.gridLength || !params.gridWidth) errors.push('Dimensiones de malla no definidas');
  if (!calculations.Rg) errors.push('Resultados de calculos no disponibles');
  
  return {
    isValid: errors.length === 0,
    errors
  };
};

/**
 * Exporta a formato CDEGS (.fot)
 */
export const exportToCDEGS = (params, calculations) => {
  const validation = validateParams(params, calculations);
  if (!validation.isValid) {
    console.error('Error de validacion:', validation.errors);
    alert(`Error al exportar a CDEGS:\n${validation.errors.join('\n')}`);
    return false;
  }

  const cdegsContent = `* CDEGS Input File for Grounding Grid Analysis
* Generated by Grounding Designer Pro - IEEE 80
* Date: ${new Date().toISOString()}
*
* PROJECT INFORMATION
* Project: ${params.projectName || 'Grounding Design'}
* Engineer: ${params.engineerName || 'N/A'}
* Location: ${params.projectLocation || 'N/A'}
*
* SOIL MODEL
* Soil Model: ${params.soilModel || 'Homogeneous'}
* Resistivity: ${params.soilResistivity} ohm-m
* Surface Layer Resistivity: ${params.surfaceLayer} ohm-m
* Surface Layer Thickness: ${params.surfaceDepth} m
* Reflection Factor: ${params.reflectionFactor || 'N/A'}
*
* GRID GEOMETRY
* Grid Dimensions: ${params.gridLength} m x ${params.gridWidth} m
* Grid Area: ${(params.gridLength * params.gridWidth).toFixed(2)} m2
* Grid Depth: ${params.gridDepth} m
* Number of Conductors X: ${params.numParallel}
* Number of Conductors Y: ${params.numParallel}
* Conductor Diameter: ${params.conductorDiameter || 0.01052} m
* Conductor Material: COPPER
* Total Conductor Length: ${calculations.totalConductor?.toFixed(2) || 0} m
*
* RODS
* Number of Rods: ${params.numRods}
* Rod Length: ${params.rodLength} m
* Rod Diameter: ${params.rodDiameter || 0.015875} m
* Total Rod Length: ${(params.numRods * params.rodLength).toFixed(2)} m
*
* FAULT DATA
* Fault Current: ${calculations.faultCurrent?.toFixed(0) || 0} A
* Division Factor Sf: ${params.currentDivisionFactor}
* Grid Current (Ig): ${calculations.Ig?.toFixed(0) || 0} A
* Fault Duration: ${params.faultDuration} s
*
* RESULTS
* Grid Resistance (Rg): ${calculations.Rg?.toFixed(3) || 0} ohm
* Ground Potential Rise (GPR): ${calculations.GPR?.toFixed(0) || 0} V
* Maximum Touch Voltage (Em): ${calculations.Em?.toFixed(0) || 0} V
* Maximum Step Voltage (Es): ${calculations.Es?.toFixed(0) || 0} V
* Allowable Touch Voltage (70kg): ${calculations.Etouch70?.toFixed(0) || 0} V
* Allowable Step Voltage (70kg): ${calculations.Estep70?.toFixed(0) || 0} V
* Safety Margin Touch: ${calculations.Etouch70 && calculations.Etouch70 > 0 ? ((calculations.Etouch70 - calculations.Em) / calculations.Etouch70 * 100).toFixed(1) : '0'}%
* Safety Margin Step: ${calculations.Estep70 && calculations.Estep70 > 0 ? ((calculations.Estep70 - calculations.Es) / calculations.Estep70 * 100).toFixed(1) : '0'}%
* Compliance Status: ${calculations.complies ? 'PASS - Design complies with IEEE 80' : 'FAIL - Design does NOT comply with IEEE 80'}
*
* END OF FILE`;

  const blob = new Blob([cdegsContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  
  try {
    a.href = url;
    a.download = `grounding_${(params.projectName || 'design').replace(/[^a-z0-9]/gi, '_')}_cdegs.fot`;
    document.body.appendChild(a);
    a.click();
    console.log('CDEGS exportado correctamente');
    return true;
  } catch (error) {
    console.error('Error exportando a CDEGS:', error);
    return false;
  } finally {
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  }
};

/**
 * Exporta a formato ETAP (.txt)
 */
export const exportToETAP = (params, calculations) => {
  const validation = validateParams(params, calculations);
  if (!validation.isValid) {
    console.error('Error de validacion:', validation.errors);
    alert(`Error al exportar a ETAP:\n${validation.errors.join('\n')}`);
    return false;
  }

  const etapContent = `[ETAP GROUNDING GRID DATA]
VERSION=6.0
DATE=${new Date().toISOString()}
PROJECT=${params.projectName || 'Grounding Design'}
ENGINEER=${params.engineerName || 'N/A'}
LOCATION=${params.projectLocation || 'N/A'}

[SOIL]
RESISTIVITY=${params.soilResistivity}
SURFACE_RESISTIVITY=${params.surfaceLayer}
SURFACE_THICKNESS=${params.surfaceDepth}
SOIL_MODEL=${params.soilModel || 'HOMOGENEOUS'}

[GRID]
LENGTH=${params.gridLength}
WIDTH=${params.gridWidth}
AREA=${(params.gridLength * params.gridWidth).toFixed(2)}
DEPTH=${params.gridDepth}
CONDUCTORS_X=${params.numParallel}
CONDUCTORS_Y=${params.numParallel}
TOTAL_CONDUCTORS=${calculations.totalConductor?.toFixed(2) || 0}
CONDUCTOR_DIAMETER=${params.conductorDiameter || 0.01052}
CONDUCTOR_MATERIAL=COPPER
CONDUCTOR_TYPE=2/0 AWG

[RODS]
COUNT=${params.numRods}
LENGTH=${params.rodLength}
DIAMETER=${params.rodDiameter || 0.015875}
TOTAL_LENGTH=${(params.numRods * params.rodLength).toFixed(2)}
MATERIAL=COPPER

[FAULT]
CURRENT=${calculations.faultCurrent?.toFixed(0) || 0}
DURATION=${params.faultDuration}
DIVISION_FACTOR=${params.currentDivisionFactor}
GRID_CURRENT=${calculations.Ig?.toFixed(0) || 0}
FAULT_TYPE=LINE_TO_GROUND

[RESULTS]
RESISTANCE=${calculations.Rg?.toFixed(3) || 0}
GPR=${calculations.GPR?.toFixed(0) || 0}
TOUCH_VOLTAGE=${calculations.Em?.toFixed(0) || 0}
STEP_VOLTAGE=${calculations.Es?.toFixed(0) || 0}
TOUCH_LIMIT_50KG=${calculations.Etouch50?.toFixed(0) || 0}
STEP_LIMIT_50KG=${calculations.Estep50?.toFixed(0) || 0}
TOUCH_LIMIT_70KG=${calculations.Etouch70?.toFixed(0) || 0}
STEP_LIMIT_70KG=${calculations.Estep70?.toFixed(0) || 0}
STATUS=${calculations.complies ? 'COMPLIANT' : 'NON_COMPLIANT'}
SAFETY_MARGIN_TOUCH=${calculations.Etouch70 && calculations.Etouch70 > 0 && calculations.Em !== 0 ? ((calculations.Etouch70 - calculations.Em) / calculations.Etouch70 * 100).toFixed(1) : '0'}
SAFETY_MARGIN_STEP=${calculations.Estep70 && calculations.Estep70 > 0 && calculations.Es !== 0 ? ((calculations.Estep70 - calculations.Es) / calculations.Estep70 * 100).toFixed(1) : '0'}

[END]`;

  const blob = new Blob([etapContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  
  try {
    a.href = url;
    a.download = `grounding_${(params.projectName || 'design').replace(/[^a-z0-9]/gi, '_')}_etap.txt`;
    document.body.appendChild(a);
    a.click();
    console.log('ETAP exportado correctamente');
    return true;
  } catch (error) {
    console.error('Error exportando a ETAP:', error);
    return false;
  } finally {
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  }
};

/**
 * Exporta a formato SKM PowerTools (.dat)
 */
export const exportToSKM = (params, calculations) => {
  const validation = validateParams(params, calculations);
  if (!validation.isValid) {
    console.error('Error de validacion:', validation.errors);
    alert(`Error al exportar a SKM:\n${validation.errors.join('\n')}`);
    return false;
  }

  const skmContent = `[SKM GROUNDING DATA]
FILE_TYPE=GROUNDING_GRID
GENERATED_BY=Grounding Designer Pro
GENERATED_ON=${new Date().toISOString()}
VERSION=2.0

[PROJECT]
NAME=${params.projectName || 'Grounding Design'}
ENGINEER=${params.engineerName || 'N/A'}
LOCATION=${params.projectLocation || 'N/A'}
DATE=${new Date().toISOString().split('T')[0]}

[PARAMETERS]
TRANSFORMER_KVA=${params.transformerKVA}
PRIMARY_VOLTAGE=${params.primaryVoltage}
SECONDARY_VOLTAGE=${params.secondaryVoltage}
IMPEDANCE=${params.transformerImpedance}
FAULT_DURATION=${params.faultDuration}
DIVISION_FACTOR=${params.currentDivisionFactor}

[SOIL]
RHO=${params.soilResistivity}
RHO_S=${params.surfaceLayer}
H_S=${params.surfaceDepth}
SOIL_TYPE=${params.soilModel || 'HOMOGENEOUS'}

[GRID]
L=${params.gridLength}
W=${params.gridWidth}
A=${(params.gridLength * params.gridWidth).toFixed(2)}
H=${params.gridDepth}
N_CONDUCTORS=${params.numParallel}
D_CONDUCTOR=${params.conductorDiameter || 0.01052}
L_CONDUCTOR=${calculations.totalConductor?.toFixed(2) || 0}

[RODS]
N_RODS=${params.numRods}
L_ROD=${params.rodLength}
D_ROD=${params.rodDiameter || 0.015875}
L_ROD_TOTAL=${(params.numRods * params.rodLength).toFixed(2)}

[CALCULATIONS]
FAULT_CURRENT=${calculations.faultCurrent?.toFixed(0) || 0}
GRID_CURRENT=${calculations.Ig?.toFixed(0) || 0}

[RESULTS]
RG=${calculations.Rg?.toFixed(4) || 0}
GPR=${calculations.GPR?.toFixed(1) || 0}
EM=${calculations.Em?.toFixed(1) || 0}
ES=${calculations.Es?.toFixed(1) || 0}
ETOUCH50=${calculations.Etouch50?.toFixed(1) || 0}
ESTEP50=${calculations.Estep50?.toFixed(1) || 0}
ETOUCH70=${calculations.Etouch70?.toFixed(1) || 0}
ESTEP70=${calculations.Estep70?.toFixed(1) || 0}
COMPLIES=${calculations.complies ? 'YES' : 'NO'}

[END_DATA]`;

  const blob = new Blob([skmContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  
  try {
    a.href = url;
    a.download = `grounding_${(params.projectName || 'design').replace(/[^a-z0-9]/gi, '_')}_skm.dat`;
    document.body.appendChild(a);
    a.click();
    console.log('SKM exportado correctamente');
    return true;
  } catch (error) {
    console.error('Error exportando a SKM:', error);
    return false;
  } finally {
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  }
};

/**
 * Exporta a formato PSCAD (.psc)
 */
export const exportToPSCAD = (params, calculations) => {
  const pscadContent = `// PSCAD Grounding Grid Data File
// Generated by Grounding Designer Pro
// Date: ${new Date().toISOString()}

BEGIN PROJECT DATA
  NAME: ${params.projectName || 'Grounding Design'}
  ENGINEER: ${params.engineerName || 'N/A'}
  DATE: ${new Date().toISOString().split('T')[0]}
END PROJECT DATA

BEGIN SOIL DATA
  RESISTIVITY: ${params.soilResistivity}
  SURFACE_RESISTIVITY: ${params.surfaceLayer}
  SURFACE_THICKNESS: ${params.surfaceDepth}
END SOIL DATA

BEGIN GRID DATA
  LENGTH: ${params.gridLength}
  WIDTH: ${params.gridWidth}
  DEPTH: ${params.gridDepth}
  CONDUCTORS: ${params.numParallel}
  RODS: ${params.numRods}
  ROD_LENGTH: ${params.rodLength}
END GRID DATA

BEGIN FAULT DATA
  CURRENT: ${calculations.faultCurrent?.toFixed(0) || 0}
  DURATION: ${params.faultDuration}
  SF: ${params.currentDivisionFactor}
END FAULT DATA

BEGIN RESULTS
  RG: ${calculations.Rg?.toFixed(4) || 0}
  GPR: ${calculations.GPR?.toFixed(1) || 0}
  EM: ${calculations.Em?.toFixed(1) || 0}
  ES: ${calculations.Es?.toFixed(1) || 0}
  COMPLIES: ${calculations.complies ? 'YES' : 'NO'}
END RESULTS`;

  const blob = new Blob([pscadContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  
  try {
    a.href = url;
    a.download = `grounding_${(params.projectName || 'design').replace(/[^a-z0-9]/gi, '_')}_pscad.psc`;
    document.body.appendChild(a);
    a.click();
    console.log('PSCAD exportado correctamente');
    return true;
  } catch (error) {
    console.error('Error exportando a PSCAD:', error);
    return false;
  } finally {
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  }
};

/**
 * Exporta a formato CSV (datos de malla)
 */
export const exportToCSV = (params, calculations) => {
  const { nx, ny } = calculations;
  const spacingX = params.gridLength / Math.max(1, nx - 1);
  const spacingY = params.gridWidth / Math.max(1, ny - 1);
  
  let csvContent = 'X (m),Y (m),Type\n';
  
  // Puntos de la malla
  for (let i = 0; i < nx; i++) {
    for (let j = 0; j < ny; j++) {
      const x = i * spacingX;
      const y = j * spacingY;
      csvContent += `${x.toFixed(3)},${y.toFixed(3)},Node\n`;
    }
  }
  
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  
  try {
    a.href = url;
    a.download = `grounding_grid_${(params.projectName || 'design').replace(/[^a-z0-9]/gi, '_')}.csv`;
    document.body.appendChild(a);
    a.click();
    console.log('CSV exportado correctamente');
    return true;
  } catch (error) {
    console.error('Error exportando a CSV:', error);
    return false;
  } finally {
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  }
};

/**
 * Exporta a todos los formatos disponibles
 */
export const exportToAllFormats = (params, calculations) => {
  const results = {
    cdegs: false,
    etap: false,
    skm: false,
    pscad: false,
    csv: false
  };
  
  try {
    results.cdegs = exportToCDEGS(params, calculations);
  } catch (error) {
    console.error('Error exporting to CDEGS:', error);
  }
  
  try {
    results.etap = exportToETAP(params, calculations);
  } catch (error) {
    console.error('Error exporting to ETAP:', error);
  }
  
  try {
    results.skm = exportToSKM(params, calculations);
  } catch (error) {
    console.error('Error exporting to SKM:', error);
  }
  
  try {
    results.pscad = exportToPSCAD(params, calculations);
  } catch (error) {
    console.error('Error exporting to PSCAD:', error);
  }
  
  try {
    results.csv = exportToCSV(params, calculations);
  } catch (error) {
    console.error('Error exporting to CSV:', error);
  }
  
  const successCount = Object.values(results).filter(v => v === true).length;
  alert(`Exportacion completada:\n- CDEGS: ${results.cdegs ? 'OK' : 'FAIL'}\n- ETAP: ${results.etap ? 'OK' : 'FAIL'}\n- SKM: ${results.skm ? 'OK' : 'FAIL'}\n- PSCAD: ${results.pscad ? 'OK' : 'FAIL'}\n- CSV: ${results.csv ? 'OK' : 'FAIL'}\n\n${successCount}/5 formatos exportados`);
  
  return results;
};

export default {
  exportToCDEGS,
  exportToETAP,
  exportToSKM,
  exportToPSCAD,
  exportToCSV,
  exportToAllFormats
};